### ISSUE TITLE
modifications I made for CASO to work with Python2.6

### ISSUE THREAD

**Issue by mariojmdavid** [IFCA/caso#20]
Hi
I made the following modifications to the code for it to work in py2.6

caso/extract/base.py

    def _get_keystone_users(self, ks_client):
        tenant_id = ks_client.tenant_id
        users = ks_client.users.list(tenant_id=tenant_id)
        # added by Mario David (david@lip.pt)
        usDict = {}
        for u in users:
            usDict[u.id] = u.name
        return  usDict
        # return {u.id: u.name for u in users}

the last 2 lines of caso/extract/nova.py

            tot_seconds = (wall.microseconds + (wall.seconds + wall.days * 24 * 3600) * 10**6) / 10**6
            records[instance_id].wall_duration = int(tot_seconds)

Further, I have substitute all
from oslo.utils import importutils
by
from oslo_utils import importutils

just to get rid of warnings of deprecation

best
Mario

**Comment by alvarolopez** [comment]
Hi Mario.

Python 2.6 is officially retired: "[With the 2.6.9 release, and five years after its first release, the Python 2.6 series is now officially retired.](https://www.python.org/download/releases/2.6.9/)" so we decided to not support Python 2.6 anymore.

The only reason to support Py2.6 would be because of RedHat EL6 based distributions, but there are [http://wiki.centos.org/AdditionalResources/Repositories/SCL](Software Collections) already available so that you can install Python 2.7 in a CentOS 6 (this is covered in the [http://caso.readthedocs.org/en/latest/installation.html#centos-6](installation instructions]).

**Comment by mariojmdavid** [comment]
hola Alvaro
OK, the only reason is that we have our fedcloud site fully in centos6 with openstack havana (yes old) and py2.6
I am working on the new version but will take some time to have fully prod
either way I have made the modifications to the code, and hope they work for now until we have the new stuff in prod

you can close the issue

best
Mario
